server:
  port: 8000

spring.application:
  name: gateway-service

logging.level.org.springframework:
        security: TRACE
#        security.oauth2: TRACE
#        web: DEBUG
#        cloud.gateway: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-id: "interviewgether"
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${CLIENT_REDIRECT_URI}
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            scope:
              - openid
        provider:
          auth-server:
            authorization-uri: ${AUTH_PROVIDER_URI}/oauth2/authorize
            token-uri: ${AUTH_PROVIDER_URI}/oauth2/token
            user-info-uri: ${AUTH_PROVIDER_URI}/userinfo
            jwk-set-uri: ${AUTH_PROVIDER_URI}/oauth2/jwks
            user-name-attribute: sub

  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://resourceserver:8080
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - TokenRelay=auth-server

        - id: web-client
          uri: http://localhost:3000
          predicates:
            - Path=/ui/**